sudo: false

language: node_js

# for now, just test on node 7
node_js:
  - 9
  - 7
  - 6

# cache yarn cache, npm cache and node_modules to make life easier. We do not want to download them each time
cache:
  directories:
    - node_modules
    - $HOME/.npm
  yarn: true

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
  - yarn install

script:
  - yarn ci:all

after_success:
  - yarn ci:coverage
